//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOauth2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class complain
    {
        public int Id { get; set; }
        public string complain_details { get; set; }
        public int user_Id { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
